export const images = {
    ic_home: require('../assets/images/ic_home.png'),
    ic_partner: require('../assets/images/ic_partner.png'),
    ic_lead: require('../assets/images/ic_lead.png'),
    ic_down: require('../assets/images/ic_down.png'),
    ic_up: require('../assets/images/ic_up.png'),
    ic_telecaller: require('../assets/images/ic_telecaller.png'),
    ic_logo: require('../assets/images/logo.png'),
    ic_logo_text: require('../assets/images/logo_text.png'),
    ic_visible: require('../assets/images/ic_visible.png'),
    ic_invisible: require('../assets/images/ic_invisible.png'),
    ic_add: require('../assets/images/ic_add.png'),
    ic_back: require('../assets/images/ic_back.png'),
    ic_partner_info: require('../assets/images/ic_info.png'),
    bg_card: require('../assets/images/bg_card.jpg'),
    ic_pdf: require('../assets/images/ic_download_pdf.png'),
    ic_image_download: require('../assets/images/ic_download_image.png'),
}